/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package carrentalsystem;

import static carrentalsystem.Functions.*;
import java.io.IOException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JRadioButton;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class AdminViewBookingDetails extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public AdminViewBookingDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        searchInput = new javax.swing.JTextField();
        selectedSearch = new javax.swing.JComboBox<>();
        searchButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayBookingInfo = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        carInfoLabel = new javax.swing.JLabel();
        deleteBookingButton = new javax.swing.JButton();
        customerDetailsPanel = new javax.swing.JPanel();
        ICDisplay = new javax.swing.JTextField();
        phoneNoDisplay = new javax.swing.JTextField();
        ICLabel = new javax.swing.JLabel();
        phoneNoLabel = new javax.swing.JLabel();
        userIDLabel = new javax.swing.JLabel();
        userIDDisplay = new javax.swing.JTextField();
        usernameLabel = new javax.swing.JLabel();
        usernameDisplay = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        emailDisplay = new javax.swing.JTextField();
        carDetailsPanel = new javax.swing.JPanel();
        carBrandLabel = new javax.swing.JLabel();
        carPlateLabel = new javax.swing.JLabel();
        carPlateDisplay = new javax.swing.JTextField();
        carIDLabel = new javax.swing.JLabel();
        carTypeDisplay = new javax.swing.JTextField();
        carIDDisplay = new javax.swing.JTextField();
        carTypeLabel = new javax.swing.JLabel();
        carBrandDisplay = new javax.swing.JTextField();
        seatNoLabel = new javax.swing.JLabel();
        seatNoDisplay = new javax.swing.JTextField();
        bookingDetailsPanel = new javax.swing.JPanel();
        bookingStatusDisplay = new javax.swing.JTextField();
        bookingStatusLabel = new javax.swing.JLabel();
        bookingIDDisplay = new javax.swing.JTextField();
        bookingIDLabel = new javax.swing.JLabel();
        startRentLabel = new javax.swing.JLabel();
        startRentDisplay = new javax.swing.JTextField();
        paymentAmountLabel = new javax.swing.JLabel();
        paymentAmountDisplay = new javax.swing.JTextField();
        endRentLabel = new javax.swing.JLabel();
        endRentDisplay = new javax.swing.JTextField();
        paymentStatusLabel = new javax.swing.JLabel();
        paymentStatusDisplay = new javax.swing.JTextField();
        declineBookingButton = new javax.swing.JButton();
        confirmBookingButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(2147483647, 1400));
        setMinimumSize(new java.awt.Dimension(811, 629));
        setResizable(false);
        setSize(new java.awt.Dimension(1112, 670));

        selectedSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Booking ID", "Customer IC", "Car ID", "Car Brand", "Booking Status", "Payment Status", "Start Rent Date (yyyy/mm/dd)", "End Rent Date (yyyy/mm/dd)", "Unconfirmed" }));

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        displayBookingInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "BID", "UID", "Name", "Car ID", "Start Rent", "End Rent", "Status", "Amount", "Payment"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        displayBookingInfo.setToolTipText("");
        displayBookingInfo.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        displayBookingInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                displayBookingInfoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(displayBookingInfo);

        carInfoLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        carInfoLabel.setText("Booking Info");

        deleteBookingButton.setText("Delete");
        deleteBookingButton.setActionCommand("");
        deleteBookingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBookingButtonActionPerformed(evt);
            }
        });

        customerDetailsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Customer Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 12))); // NOI18N

        ICDisplay.setEditable(false);

        phoneNoDisplay.setEditable(false);

        ICLabel.setText("IC:");

        phoneNoLabel.setText("Phone No:");

        userIDLabel.setText("User ID:");

        userIDDisplay.setEditable(false);

        usernameLabel.setText("Name:");

        usernameDisplay.setEditable(false);

        emailLabel.setText("Email:");

        emailDisplay.setEditable(false);

        javax.swing.GroupLayout customerDetailsPanelLayout = new javax.swing.GroupLayout(customerDetailsPanel);
        customerDetailsPanel.setLayout(customerDetailsPanelLayout);
        customerDetailsPanelLayout.setHorizontalGroup(
            customerDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customerDetailsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(customerDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(customerDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(userIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(usernameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(customerDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(emailDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                    .addComponent(usernameDisplay)
                    .addComponent(userIDDisplay))
                .addGap(35, 35, 35)
                .addGroup(customerDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(phoneNoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ICLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(customerDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ICDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneNoDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        customerDetailsPanelLayout.setVerticalGroup(
            customerDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerDetailsPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(customerDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userIDLabel)
                    .addComponent(userIDDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(customerDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLabel)
                    .addComponent(usernameDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ICLabel)
                    .addComponent(ICDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(customerDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel)
                    .addComponent(emailDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneNoLabel)
                    .addComponent(phoneNoDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        carDetailsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Car Rented", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 12)))); // NOI18N

        carBrandLabel.setText("Car Brand:");

        carPlateLabel.setText("Car Plate:");

        carPlateDisplay.setEditable(false);

        carIDLabel.setText("Car ID:");

        carTypeDisplay.setEditable(false);

        carIDDisplay.setEditable(false);

        carTypeLabel.setText("Car Type:");

        carBrandDisplay.setEditable(false);

        seatNoLabel.setText("Seat No:");

        seatNoDisplay.setEditable(false);

        javax.swing.GroupLayout carDetailsPanelLayout = new javax.swing.GroupLayout(carDetailsPanel);
        carDetailsPanel.setLayout(carDetailsPanelLayout);
        carDetailsPanelLayout.setHorizontalGroup(
            carDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(carDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(carPlateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(carIDLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(carBrandLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(carDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(carDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(carBrandDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                        .addComponent(carIDDisplay))
                    .addComponent(carPlateDisplay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(carDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(carDetailsPanelLayout.createSequentialGroup()
                        .addComponent(carTypeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(carTypeDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(carDetailsPanelLayout.createSequentialGroup()
                        .addComponent(seatNoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(seatNoDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        carDetailsPanelLayout.setVerticalGroup(
            carDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, carDetailsPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(carDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(carIDLabel)
                    .addComponent(carIDDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(carDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(carBrandLabel)
                    .addComponent(carTypeLabel)
                    .addComponent(carBrandDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carTypeDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(carDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(carPlateLabel)
                    .addComponent(seatNoLabel)
                    .addComponent(seatNoDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carPlateDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        bookingDetailsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Booking ID & Status", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 12))); // NOI18N
        bookingDetailsPanel.setName(""); // NOI18N

        bookingStatusDisplay.setEditable(false);

        bookingStatusLabel.setText("Booking Status:");

        bookingIDDisplay.setEditable(false);

        bookingIDLabel.setText("Booking ID:");

        startRentLabel.setText("Start Rent Date:");

        startRentDisplay.setEditable(false);

        paymentAmountLabel.setText("Payment Amount:");

        paymentAmountDisplay.setEditable(false);

        endRentLabel.setText("End Rent Date:");

        endRentDisplay.setEditable(false);

        paymentStatusLabel.setText("Payment Status:");

        paymentStatusDisplay.setEditable(false);

        javax.swing.GroupLayout bookingDetailsPanelLayout = new javax.swing.GroupLayout(bookingDetailsPanel);
        bookingDetailsPanel.setLayout(bookingDetailsPanelLayout);
        bookingDetailsPanelLayout.setHorizontalGroup(
            bookingDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookingDetailsPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(bookingDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bookingDetailsPanelLayout.createSequentialGroup()
                        .addComponent(paymentAmountLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(paymentAmountDisplay))
                    .addGroup(bookingDetailsPanelLayout.createSequentialGroup()
                        .addGroup(bookingDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bookingIDLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(bookingDetailsPanelLayout.createSequentialGroup()
                                .addComponent(startRentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bookingDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(startRentDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(bookingIDDisplay))))
                .addGap(55, 55, 55)
                .addGroup(bookingDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bookingDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(endRentLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bookingStatusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                    .addComponent(paymentStatusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bookingDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bookingStatusDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(endRentDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paymentStatusDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );
        bookingDetailsPanelLayout.setVerticalGroup(
            bookingDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bookingDetailsPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(bookingDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bookingDetailsPanelLayout.createSequentialGroup()
                        .addGroup(bookingDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bookingStatusLabel)
                            .addComponent(bookingStatusDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bookingDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(endRentLabel)
                            .addComponent(endRentDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(bookingDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(paymentStatusLabel)
                            .addComponent(paymentStatusDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(bookingDetailsPanelLayout.createSequentialGroup()
                        .addGroup(bookingDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bookingIDLabel)
                            .addComponent(bookingIDDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bookingDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(startRentDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(startRentLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bookingDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(paymentAmountLabel)
                            .addComponent(paymentAmountDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(17, 17, 17))
        );

        declineBookingButton.setText("Decline");
        declineBookingButton.setVisible(false);
        declineBookingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                declineBookingButtonActionPerformed(evt);
            }
        });

        confirmBookingButton.setText("Confirm");
        confirmBookingButton.setVisible(false);
        confirmBookingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBookingButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 145, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(398, 398, 398)
                                        .addComponent(confirmBookingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(declineBookingButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(customerDetailsPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 560, Short.MAX_VALUE)
                                    .addComponent(bookingDetailsPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(carDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(deleteBookingButton)
                                                .addGap(12, 12, 12))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(51, 51, 51)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(carInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(selectedSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchInput, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(searchButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1015, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1053, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(carInfoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectedSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deleteBookingButton)
                            .addComponent(declineBookingButton)
                            .addComponent(confirmBookingButton))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(carDetailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bookingDetailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(customerDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(16, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68))))
        );

        bookingDetailsPanel.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        String input = selectedSearch.getSelectedItem().toString();
        String searchText = searchInput.getText();
        ArrayList<Booking> bookingDetails = showBookingInfo(input, searchText);
        DisplayBookingsTable(bookingDetails); 
        if(input.equalsIgnoreCase("Unconfirmed")){
            confirmBookingButton.setVisible(true);
            declineBookingButton.setVisible(true);
            deleteBookingButton.setVisible(false);
        }
        searchInput.setText(null);
        
        carIDDisplay.setText(null);
        carBrandDisplay.setText(null);
        carTypeDisplay.setText(null);
        carPlateDisplay.setText(null);
        seatNoDisplay.setText(null);
        
        bookingIDDisplay.setText(null);
        bookingStatusDisplay.setText(null);
        startRentDisplay.setText(null);
        endRentDisplay.setText(null);
        paymentAmountDisplay.setText(null);
        paymentStatusDisplay.setText(null);

        userIDDisplay.setText(null);
        usernameDisplay.setText(null);
        ICDisplay.setText(null);
        emailDisplay.setText(null);
        phoneNoDisplay.setText(null);
    }//GEN-LAST:event_searchButtonActionPerformed

    private void displayBookingInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_displayBookingInfoMouseClicked
        if(evt.getClickCount()>=2){
            int row = displayBookingInfo.getSelectedRow();
            setBookingDetails(row);
        }
    }//GEN-LAST:event_displayBookingInfoMouseClicked
    
    private void deleteBookingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBookingButtonActionPerformed
        ArrayList<Booking> bookingList = readTextFile("booking");
        ArrayList<Booking> updatedBookingList = new ArrayList<>();
        String id = bookingIDDisplay.getText();

        for(Booking i : bookingList){
           if(!i.getBookingID().equals(id)){
                updatedBookingList.add(i);     
            } 
        }
        
        try { 
            updateBookingDetails(updatedBookingList);
        } catch (IOException ex) {
            messageBox("Error occured! Please try again!");
            Logger.getLogger(AdminViewBookingDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        searchInput.setText(null);
        
        carIDDisplay.setText(null);
        carBrandDisplay.setText(null);
        carTypeDisplay.setText(null);
        carPlateDisplay.setText(null);
        seatNoDisplay.setText(null);
        
        bookingIDDisplay.setText(null);
        bookingStatusDisplay.setText(null);
        startRentDisplay.setText(null);
        endRentDisplay.setText(null);
        paymentAmountDisplay.setText(null);
        paymentStatusDisplay.setText(null);

        userIDDisplay.setText(null);
        usernameDisplay.setText(null);
        ICDisplay.setText(null);
        emailDisplay.setText(null);
        phoneNoDisplay.setText(null);
    }//GEN-LAST:event_deleteBookingButtonActionPerformed

    private void confirmBookingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBookingButtonActionPerformed
        ArrayList<Booking> bookingList = readTextFile("booking");
        ArrayList<Booking> updatedBookingList = new ArrayList<>();
        String id = bookingIDDisplay.getText();
        
        for(Booking i : bookingList){
            if(i.getBookingID().equals(id)){
                i.setBookingStatus("Unconfirmed");
                updatedBookingList.add(i);
                
            }
            else{
                updatedBookingList.add(i);                
            }
        }
        
        try {
            updateBookingDetails(updatedBookingList);            
        } catch (IOException ex) {
            Logger.getLogger(AdminViewBookingDetails.class.getName()).log(Level.SEVERE, null, ex);
            messageBox("Error occured! Please try again!");
        }
        
        searchInput.setText(null);
        carIDDisplay.setText(null);
        carBrandDisplay.setText(null);
        carTypeDisplay.setText(null);
        carPlateDisplay.setText(null);
        seatNoDisplay.setText(null);
        
        bookingIDDisplay.setText(null);
        bookingStatusDisplay.setText(null);
        startRentDisplay.setText(null);
        endRentDisplay.setText(null);
        paymentAmountDisplay.setText(null);
        paymentStatusDisplay.setText(null);

        userIDDisplay.setText(null);
        usernameDisplay.setText(null);
        ICDisplay.setText(null);
        emailDisplay.setText(null);
        phoneNoDisplay.setText(null);
    }//GEN-LAST:event_confirmBookingButtonActionPerformed

    private void declineBookingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_declineBookingButtonActionPerformed
        ArrayList<Booking> bookingList = readTextFile("booking");
        ArrayList<Booking> updatedBookingList = new ArrayList<>();
        String id = bookingIDDisplay.getText();
        
        
        for(Booking i : bookingList){
            if(i.getBookingID().equals(id)){
                i.setBookingStatus("Declined");
                updatedBookingList.add(i);
                
            }
            else{
                updatedBookingList.add(i);                
            }
        }
        
        try {
            updateBookingDetails(updatedBookingList);
        } catch (IOException ex) {
            Logger.getLogger(AdminViewBookingDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        searchInput.setText(null);
        carIDDisplay.setText(null);
        carBrandDisplay.setText(null);
        carTypeDisplay.setText(null);
        carPlateDisplay.setText(null);
        seatNoDisplay.setText(null);
        
        bookingIDDisplay.setText(null);
        bookingStatusDisplay.setText(null);
        startRentDisplay.setText(null);
        endRentDisplay.setText(null);
        paymentAmountDisplay.setText(null);
        paymentStatusDisplay.setText(null);

        userIDDisplay.setText(null);
        usernameDisplay.setText(null);
        ICDisplay.setText(null);
        emailDisplay.setText(null);
        phoneNoDisplay.setText(null);
    }//GEN-LAST:event_declineBookingButtonActionPerformed
    
    //show booking details after clicked from table
    private void setBookingDetails(int row){
        ArrayList<Booking> bookingList = readTextFile("booking");
        ArrayList<Member> memberList = readTextFile("member");
        ArrayList<Car> carList = readTextFile("car");  
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm");
        
        String bookingID = displayBookingInfo.getModel().getValueAt(row, 0).toString();
        String userID = displayBookingInfo.getModel().getValueAt(row, 1).toString();
        String carID = displayBookingInfo.getModel().getValueAt(row, 3).toString();
        for(Booking b : bookingList){
            if(bookingID.equals(b.getBookingID())){
                bookingIDDisplay.setText(b.getBookingID());
                bookingStatusDisplay.setText(b.getBookingStatus());
                startRentDisplay.setText(b.getStartDate().format(formatter));
                endRentDisplay.setText(b.getEndDate().format(formatter));
                paymentAmountDisplay.setText(String.valueOf(b.getPaymentAmount()));
                paymentStatusDisplay.setText(b.getPaymentStatus());
            }
        }
        
        for(Member m : memberList){
            if(userID.equals(m.getUid())){
                userIDDisplay.setText(m.getUid());
                usernameDisplay.setText(m.getName());
                ICDisplay.setText(String.valueOf(m.getIcNo()));
                emailDisplay.setText(m.getEmail());
                phoneNoDisplay.setText(String.valueOf(m.getPhoneNo()));
            }
        }
        
        for(Car c : carList){
            if(carID.equals(c.getCarID())){
                carIDDisplay.setText(c.getCarID());
                carBrandDisplay.setText(c.getBrand());
                carTypeDisplay.setText(c.getCarType());
                carPlateDisplay.setText(c.getCarPlate());
                seatNoDisplay.setText(String.valueOf(c.getSeatNum()));
            }
        }
    }
    private ArrayList showBookingInfo(String input, String searchText){
        ArrayList<Booking> bookingList = readTextFile("booking");
        ArrayList<Member> memberList = readTextFile("member");
        ArrayList<Car> carList = readTextFile("car");
        ArrayList <Booking> bookingDetails = new ArrayList<>();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm");

        try {
            switch (input) {
                case "Booking ID":
                    for(Booking b : bookingList) {
                        if (searchText.equalsIgnoreCase(b.getBookingID())) {
                            bookingDetails.add(b);
                        }
                    }
                    return bookingDetails;    
                
                    
                case "Customer IC":
                    for(Member m : memberList) {
                        if(searchText.equals(m.getIcNo())){
                            for(Booking b : bookingList){                               
                                if (m.getUid().equals(b.getMember().getUid())) {
                                    bookingDetails.add(b);
                                }   
                            }
                        }   
                    }
                    return bookingDetails;

                case "Car ID":
                    for (Booking b : bookingList) {    
                        if (searchText.equalsIgnoreCase(b.getCar().getCarID())) {
                            bookingDetails.add(b);
                        }
                    }
                    return bookingDetails;
                    
                    
                case "Car Brand":
                    for(Car c : carList){
                        if(searchText.equalsIgnoreCase(c.getBrand())){
                           for (Booking b : bookingList) {    
                                if (c.getCarID().equals(b.getCar().getCarID())) {
                                    bookingDetails.add(b);
                                }
                            } 
                        }
                    }
                    return bookingDetails;

                case "Start Rent Date (yyyy/mm/dd)": 
                    String startDate = searchText + " 00:00";
                    LocalDateTime startRentDate = LocalDateTime.parse(startDate, formatter);
                    LocalDateTime startRentDateRange = startRentDate.plusDays(1);

                    for (Booking b : bookingList) {
                        if  (b.getStartDate().isAfter(startRentDate) && b.getStartDate().isBefore(startRentDateRange)) {
                            bookingDetails.add(b);
                        }
                    }
                    return bookingDetails;

                case "End Rent Date (yyyy/mm/dd)":
                    String endDate = searchText + " 00:00";
                    LocalDateTime endRentDate = LocalDateTime.parse(endDate, formatter);
                    LocalDateTime endRentDateRange = endRentDate.plusDays(1);

                    for (Booking b : bookingList) {
                        if  (b.getEndDate().isAfter(endRentDate) && b.getEndDate().isBefore(endRentDateRange)) {
                            bookingDetails.add(b);
                        }
                    }
                    return bookingDetails;
                    
                case "Booking Status":
                    for (Booking b : bookingList) {
                        if (searchText.equalsIgnoreCase(b.getBookingStatus())) {
                            bookingDetails.add(b);
                        }
                    }
                    return bookingDetails;
                    
                case "Payment Status":
                    for (Booking b : bookingList) {
                        if (searchText.equalsIgnoreCase(b.getPaymentStatus())) {
                            bookingDetails.add(b);
                        }
                    }
                    return bookingDetails;
                    
                case "Unconfirmed":
                    for (Booking b : bookingList) {
                        if (b.getBookingStatus().equalsIgnoreCase("Unconfirmed")) {
                            bookingDetails.add(b);
                        }
                    }
                    return bookingDetails;
            }

        } catch (IllegalArgumentException e) {
            messageBox("Details not found! Please try again!");
            Logger.getLogger(AdminViewCarDetails.class.getName()).log(Level.SEVERE, null, e);
            
        }
        return null;
    }
    
    private void DisplayBookingsTable(ArrayList<Booking> bookingList) { 
        ArrayList<Member> memberList = readTextFile("member");
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm");
        String username = null;
        
        try {
            DefaultTableModel tableModel = (DefaultTableModel)displayBookingInfo.getModel();
            tableModel.setRowCount(0);

            //get and set data to table
            if(!bookingList.isEmpty()){
                for(Booking b : bookingList){
                    String bookID = b.getBookingID();
                    String UID = b.getMember().getUid();                   
                    String carID = b.getCar().getCarID();
                    String startRent = b.getStartDate().format(formatter);
                    String endRent = b.getEndDate().format(formatter);
                    String bookingStatus = b.getBookingStatus();
                    Double payAmount = b.getPaymentAmount();
                    String paymentStatus = b.getPaymentStatus();
                    
                    for(Member m : memberList){
                        if(b.getMember().getUid().equalsIgnoreCase(m.getUid())){
                            username = m.getName();
                        }
                    }
                    
                    
                    Object[] data = {bookID, UID, username, carID, startRent, endRent, bookingStatus, payAmount, paymentStatus};
                    tableModel.addRow(data);
                }
            }
            else{
                String[] noRecord = {"No records."};
                tableModel.addRow(noRecord);
            }
            
        } catch (Exception e) {
            messageBox("Details not found! Please try again!");
            Logger.getLogger(AdminViewCarDetails.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminViewBookingDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminViewBookingDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminViewBookingDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminViewBookingDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminViewBookingDetails().setVisible(true);
                
            }
            
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ICDisplay;
    private javax.swing.JLabel ICLabel;
    private javax.swing.JPanel bookingDetailsPanel;
    private javax.swing.JTextField bookingIDDisplay;
    private javax.swing.JLabel bookingIDLabel;
    private javax.swing.JTextField bookingStatusDisplay;
    private javax.swing.JLabel bookingStatusLabel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField carBrandDisplay;
    private javax.swing.JLabel carBrandLabel;
    private javax.swing.JPanel carDetailsPanel;
    private javax.swing.JTextField carIDDisplay;
    private javax.swing.JLabel carIDLabel;
    private javax.swing.JLabel carInfoLabel;
    private javax.swing.JTextField carPlateDisplay;
    private javax.swing.JLabel carPlateLabel;
    private javax.swing.JTextField carTypeDisplay;
    private javax.swing.JLabel carTypeLabel;
    private javax.swing.JButton confirmBookingButton;
    private javax.swing.JPanel customerDetailsPanel;
    private javax.swing.JButton declineBookingButton;
    private javax.swing.JButton deleteBookingButton;
    private javax.swing.JTable displayBookingInfo;
    private javax.swing.JTextField emailDisplay;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField endRentDisplay;
    private javax.swing.JLabel endRentLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField paymentAmountDisplay;
    private javax.swing.JLabel paymentAmountLabel;
    private javax.swing.JTextField paymentStatusDisplay;
    private javax.swing.JLabel paymentStatusLabel;
    private javax.swing.JTextField phoneNoDisplay;
    private javax.swing.JLabel phoneNoLabel;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchInput;
    private javax.swing.JTextField seatNoDisplay;
    private javax.swing.JLabel seatNoLabel;
    private javax.swing.JComboBox<String> selectedSearch;
    private javax.swing.JTextField startRentDisplay;
    private javax.swing.JLabel startRentLabel;
    private javax.swing.JTextField userIDDisplay;
    private javax.swing.JLabel userIDLabel;
    private javax.swing.JTextField usernameDisplay;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
